// export this variable in order to use it in any file 
export const analyticsDataSet = {
    // objext has several objects inside 
    // please add all variebles that you need here 
    // delete all comments in the end 
    events: {
        clickFollow: "click_follow",
        clickFollowTop: "click_follow_top",
        pageViewFollowTop: "pageview_follow_top",
        showCreateAccountSuccess: "show_create_account_success",
        pageviewStream: "pageview_stream",
        clickSendGift: "click_send_gift",
        showGiftSent: "show_gift_sent",
        clickGetCoins: "click_get_coins",
        previewCoinShop: "pageview_coins_shop",
        showCoinShop: "show_coins_shop",
        clickBuyPack: "click_buy_pack",
        pageViewPayingMenu: "pageview_payingMenu",
        clickClosePayingMenu: "click_payingMenu_close",
        showPayingMenuSuccess: "show_payingMenu_success",
        showPremiumJoin: "show_premium_join",
        clickPremiumJoin: "click_premium_join",
        showRoomJoin: "show_room_join",
        clickRoomJoin: "click_room_join",
        clickGiftShop: "click_gifts_shop",
        clickSave: "click_save",
        pageviewUserInfo: "pageview_user_info",
        clickSkipProfileSetUp: "click_skip_profile_set_up",
        clickLogout: "click_logout",
        clickDeleteProfile: "click_delete_profile",
        showReasonDelete: "show_reason_delete",
        clickConfirmDeleteProfile: "click_confirm_delete_profile",
        profileDeletedSuccess: "profile_deleted_success",
        showConfirmDelete: "show_confirm_delete",
        clickProfile: "click_profile",
        pageviewEditProfile: "pageview_edit_profile",
        clickPhotoEdit: "click_photo_edit",
        clickSaveProfile: "click_save_profile",
        clickSettings: "click_settings",
        pageviewSettings: "pageview_settings",
        clickFollowers: "click_followers",
        pageviewFollowers: "pageview_followers",
        clickMyFollowings: "click_my_followings",
        clickMyFollowers: "click_my_followers",
        pageviewMyFollowings: "pageview_my_followings",
        clickRefferalProgram: "click_refferal_program",
        pageviewReferralProgram: "pageview_referral_program",
        clickRedeemCash: "click_redeem_cash",
        pageviewTransactionsHistory: "pageview_transactions_history",
        clickTopGifters: "click_top_gifters",
        pageviewTopGifters: "pageview_top_gifters",
        clickMyVipStatus: "click_my_vip_status",
        pageviewMyVipStatus: "pageview_my_vip_status",
        showGiftReceived: "show_gift_received",
        clickGiftsShop: "click_gifts_shop",
        showGiftsShop: "show_gifts_shop",
        clickStartStream: "click_start_stream",
        clickStream: "click_stream",
        clickCoinsShop: "click_coins_shop",
        pageviewСoinsShop: "pageview_coins_shop",
        pageviewFollowings: "pageview_followings",
        clickFollowings: "click_followings",
        pageviewAllStreams: "pageview_all_streams",
        clickLeaderboard: "click_leaderboard",
        clickCloseShop: "click_close_shop",
        pageviewNoInternet: "pageview_no_internet",
        showStartPremiumGifts: "show_start_premium_gifts",
        clickStartPremiumGifts: "click_start_premium_gifts",
        showInviteTopGifters: "show_invite_top_gifters",
        clickInviteTopGifters: "click_invite_top_gifters",
        showInvitesSent: "show_invites_sent",
        showPopupEndStream: "show_popup_end_stream",
        showPopupEndPremium: "show_popup_end_premium",
        clickCloseStream: "click_close_stream",
        clickPreviewStream: "click_preview_stream",
        pageviewPreviewStream: "pageview_preview_stream",
        pageviewGoLive: "pageview_go_live",
        clickGoLive: "click_go_live",
        showInappropriateTitle: "show_inappropriate_title",
        showSetPhoto: "show_set_photo",
        clickSetPhoto: "click_set_photo",
        startBeautyFilterDownload: "start_beauty_filter_download",
        beautyFilterDownloadSuccess: "beauty_filter_download_success",
        beautyFilterDownloadFailed: "beauty_filter_download_failed",
        newStreamStarted: "new_stream_started",
        clickEndStream: "click_end_stream",
        clickPauseStream: "click_pause_stream",
        streamShared: "stream_shared",
        clickChooseSticker: "click_choose_sticker",
        showAddStickerText: "show_add_sticker_text",
        clickAddStickerText: "click_add_sticker_text",
        showInappropriateStickerText: "show_inappropriate_sticker_text",
        showAddSticker: "show_add_sticker",
        showStickerAdded: "show_sticker_added",
        clickChangeSticker: "click_change_sticker",
        clickDeleteDesiredGift: "click_delete_desired_gift",
        clickBeautyFilter: "click_beauty_filter",
        showEditBeautyFilter: "show_edit_beauty_filter",
        showBeautyFilterAdded: "show_beauty_filter_added",
        beautyFilterError: "beauty_filter_error",
        showEndStream: "show_end_stream",
        beautyFeedback: "beauty_feedback",
        clickEndConfirmation: "click_end_confirmation",
        showBroadcastEnded: "show_broadcast_ended",
        clickChangeStreamType: "click_change_stream_type",
        showInviteStreamer: "show_invite_streamer",
        showStreamerInvited: "show_streamer_invited",
        clickInviteStreamerAnswer: "click_invite_streamer_answer",
        showInviteStreamerRequest: "show_invite_streamer_request",
        showInviteStreamerAccepted: "show_invite_streamer_accepted",
        showInviteStreamerRejected: "show_invite_streamer_rejected",
        showBattleResults: "show_battle_results",
        swipeTutorial: "swipe_tutorial",
        swipeUi: "swipe_ui",
        streamSwipe: "stream_swipe",
        showStreamPaused: "show_stream_paused",
        showPopupFollow: "show_popup_follow",
        clickMessage: "click_message",
        clickShare: "click_share",
        showProfilePreview: "show_profile_preview",
        clickBlock: "click_block",
        userBlocked: "user_blocked",
        clickReport: "click_report",
        reportSend: "report_send",
        showPushInviteToPremium: "show_push_invite_to_premium",
        showPushInviteToRoom: "show_push_invite_to_room",
        clickTranslate: "click_translate",
        giftShopSwipe: "gift_shop_swipe",
        clickChatMessages: "click_chat_messages",
        pageviewStreamEnded: "pageview_stream_ended",


    },

    context: {
        spalsh: "Splash",
        startStream: "Start Stream",
        watchersStream: "Watcher's Stream",
        buynow: "Buynow",
        chat: "Chat",
        coinsshop: "Coins Shop",
        accountManagement: "Account management",
        profile: "Profile",
        referral: "Referral",
        streamersStream: "Streamer's Stream",
        allStreams: "All streams",
        followings: "Followings",
        noInternet: "No internet",
        push: "Push",

    }
}

